version: '2'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - demo

  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 3306:3306
    networks:
    - demo

  prometheus:
    image: prom/prometheus:v2.15.1
    volumes:
    - ./prometheus/:/etc/prometheus/
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
    networks:
    - demo

  prometheus-proxy:
    image: micrometermetrics/prometheus-rsocket-proxy:0.9.0
    ports:
    - 18080:8080
    - 8081:8081
    - 7001:7001
    mem_limit: 256m
    environment:
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k"
    - MANAGEMENT_METRICS_TAGS_APPLICATION=prometheus-proxy
    - MANAGEMENT_METRICS_TAGS_ORGANIZATION=system
    - MANAGEMENT_METRICS_TAGS_SPACE=monitoring-tools
    - MANAGEMENT_METRICS_TAGS_INSTANCE_ID=prometheus-proxy:0
    networks:
    - demo

  grafana:
    image: grafana/grafana:6.5.2
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
    - demo

  zipkin-server:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411
    mem_limit: 256m
    environment:
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k"
    networks:
    - demo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
    - 9200:9200
    environment:
    - discovery.type=single-node
    - cluster.name=demo
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
    - demo

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    networks:
    - demo

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    volumes:
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    - /tmp:/tmp/logs
    environment:
    - "LS_JAVA_OPTS=-Xms768m -Xmx768m"
    mem_limit: 1G
    ports:
    - 5514:5514
    depends_on:
    - elasticsearch
    networks:
    - demo

networks:
  demo:
    external: true
