version: '3'

services:
  # Infrastructure
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - demo

  # Monitoring
  zipkin-server:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411
    networks:
    - demo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
    - 9200:9200
    environment:
    - discovery.type=single-node
    - cluster.name=demo
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
    - demo

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    networks:
    - demo

networks:
  demo:
    external: true
