version: '2'

services:
  gateway-server:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 8080:8080
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - UI_URL=http://ui
    - WEB_URL=http://store-web:9000
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./gateway-server/target:/app
    working_dir: /app
    command: java -jar /app/gateway-server-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  # UI
  ui:
    build: ./ui/
    ports:
    - "8000:80"
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  # Services
  store-web:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9000:9000
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - ITEM_URL=http://item-service:9001
    - STOCK_URL=http://stock-service:9002
    - CART_URL=http://cart-service:9003
    - ORDER_URL=http://order-service:9004
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./store-web/target:/app
    working_dir: /app
    command: java -jar /app/store-web-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  item-service:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9001:9001
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/item
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./item/item-service/target:/app
    working_dir: /app
    command: java -jar /app/item-service-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  stock-service:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9002:9002
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./stock/stock-service/target:/app
    working_dir: /app
    command: java -jar /app/stock-service-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  cart-service:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9003:9003
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cart
    - ITEM_URL=http://item-service:9001
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./cart/cart-service/target:/app
    working_dir: /app
    command: java -jar /app/cart-service-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  order-service:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9004:9004
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_RABBITMQ_HOST=rabbit-mq
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order
    - STOCK_URL=http://stock-service:9002
    - CART_URL=http://cart-service:9003
    - PAYMENT_URL=http://payment-service:9005
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./order/order-service/target:/app
    working_dir: /app
    command: java -jar /app/order-service-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

  payment-service:
    image: adoptopenjdk/openjdk11:alpine-slim
    ports:
    - 9005:9005
    mem_limit: 256m
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - SERVER_TOMCAT_MAX_THREADS=4
    - SPRING_RABBITMQ_HOST=rabbit-mq
    - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/
    - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST=prometheus-proxy
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment
    - "_JAVA_OPTIONS=-Xmx80m -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo"
    volumes:
    - ./payment/payment-service/target:/app
    working_dir: /app
    command: java -jar /app/payment-service-1.0.0.jar
    networks:
    - demo
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5514
        syslog-format: rfc5424

networks:
  demo:
    external: true
