global:
  scrape_interval: 10s
  scrape_timeout: 9s
  evaluation_interval: 10s
scrape_configs:
- job_name: 'proxied-applications'
  metrics_path: '/metrics/connected'
  static_configs:
  - targets:
    - prometheus-proxy:8080
- job_name: 'proxies'
  metrics_path: '/metrics/proxy'
  static_configs:
  - targets:
    - prometheus-proxy:8080
